# .bashrc

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Source global definitions
. /etc/bash/bashrc

color_prompt=yes
force_color_prompt=yes
unset PROMPT_COMMAND

PS1='[\[\033[01;3;32m\]\u@\h\[\033[00m\]:\[\033[1;33m\]${?}\[\033[0;0m\] \[\033[01;34m\]\w\[\033[00m\]]$ '

# Trim dirs to 3
PROMPT_DIRTRIM=2

# Completion
shopt -s cdspell cdable_vars
shopt -s direxpand dirspell
shopt -s progcomp_alias

# Don't quit with running jobs
shopt -s checkjobs

# Aliases
alias sane="stty sane"
alias ls="ls --color=auto"
